name: CI - Tests and Integration
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Unit test
        run: go test -v ./...

      - name: Integration test
        run: bash test/run.sh

      - name: Bash completion tests
        run: |
          echo "Checking bash completion environment..."
          bash --version
          echo "BASH_VERSION: $BASH_VERSION"
          echo "Running bash completion test suite (191 tests across 18 suites)..."
          ./completion/tests/run_all_tests.sh

      - name: Try executing the README
        run: go install && markdown-runner
